slogan: "欢迎访问黄复得的博客！"

menu:
  - title: 文章列表
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: 分类
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: 标签云
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: 关于我
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "黄复得"
    url: http://www.huangfude.com/
    intro: "黄复得的博客"
    icon: "fa fa-link"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname:

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR